services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    networks:
      - postgres-network
    depends_on:
      - database
  
  database:
    image: postgres
    environment:
      POSTGRES_DB: MyDatabase
      POSTGRES_USER: admin
      POSTGRES_PASSWORD : password
    ports:
      - 5432:5432
    networks:
      - postgres-network
  
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 15432:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    depends_on:
      - database
    networks:
      - postgres-network

networks: 
  postgres-network:
    driver: bridge
