# Use a Python image with uv pre-installed
FROM ghcr.io/astral-sh/uv:python3.12-bookworm-slim

# Install the project into `/testing`
WORKDIR /testing

# Enable bytecode compilation
ENV UV_COMPILE_BYTECODE=1

# Copy from the cache instead of linking since it's a mounted volume
ENV UV_LINK_MODE=copy

# Install the project's dependencies using the lockfile and settings
RUN --mount=type=cache,target=/root/.cache/uv \
    --mount=type=bind,source=uv.lock,target=uv.lock \
    --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
    uv sync --frozen --group test

# Then, add the rest of the project source code
# Installing separately from its dependencies allows optimal layer caching
ADD . /testing



# Place executables in the environment at the front of the path
ENV PATH="/testing/.venv/bin:$PATH"

# Reset the entrypoint, don't invoke `uv`
ENTRYPOINT []

# Default command to run tests
# CMD ["pytest", "--maxfail=1", "--disable-warnings", "-v"]

CMD ["pytest", "./tests/"]
